CREATE TABLE produit
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    design VARCHAR(80)                             NOT NULL,
    stock  INTEGER DEFAULT 0,
    CONSTRAINT pk_produit PRIMARY KEY (id)
);

CREATE TABLE fournisseur
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_fournisseur PRIMARY KEY (id)
);

CREATE TABLE approvisionnement
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fournisseur_id BIGINT                                  NOT NULL,
    produit_id     BIGINT                                  NOT NULL,
    quantite       INTEGER DEFAULT 0,
    CONSTRAINT pk_approvisionnement PRIMARY KEY (id),
    CONSTRAINT fk_approvisionnement_fournisseur_id FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) ON DELETE CASCADE,
    CONSTRAINT fk_approvisionnement_produit_id FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE
);

CREATE TABLE audit_approvisionnement
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action              VARCHAR(13)                             NOT NULL,
    date                timestamptz                             NOT NULL,
    nom_fournisseur     VARCHAR(50)                             NOT NULL,
    produit_designation VARCHAR(80)                             NOT NULL,
    qte_entree_ancien   INTEGER      DEFAULT 0,
    qte_entree_nouveau  INTEGER      DEFAULT 0,
    utilisateur         VARCHAR(255) DEFAULT '__SYSTEM__',
    CONSTRAINT pk_audit_approvisionnement PRIMARY KEY (id),
    CONSTRAINT action_name CHECK (action IN ('INSERT', 'UPDATE', 'DELETE'))
);
